version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: "air"
    tty: true
    stdin_open: true
    volumes:
      - ./app:/go/src/app
    ports:
      - 8080:8080
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_study
      MYSQL_USER: writeitgo
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data:
    driver: local